### ISSUE TITLE
Materialization incremental should not create a temporary table when strategy is append

### ISSUE THREAD

**Issue by Marnixvdb** [dremio/dbt-dremio#118]
Materialization Incremental creates a temporary table on the target data system with the increment that needs to be processed, before applying the configured load strategy. 

As a generic pattern, this make sense. 

However, it doesn't fit well with Dremio's architecture, especially when using an append-only pattern, the only incremental loading strategy currently supported by the dbt-dremio adapter. Flushing the model to a temporary table before inserting it in the target table increases storage usage (even though it's temporary), network IO and processing time, without adding a benefit. 

In my Dremio projects, I could of course adjust the materialization incremental macro to use a temporary view instead. Since I'm not a fan of maintaining this type of macro customizations, I'd rather see the Dremio adapter handle this more intelligently.

If you are open to this change, I can write it and submit a PR.

**Comment by ArgusLi** [comment]
Hi Marnix,

Are you using our 1.3.0 release? We recently changed our incremental materialization to match that of dbt-core. I believe the rationale behind it is to be more error-proof. Having a temporary table as you said does have drawbacks, but the biggest advantage is that it ensures if anything goes wrong there will be a back up table that will not be affected.

**Comment by Marnixvdb** [comment]
yes, I'm using 1.3.0 - sorry, I should have stated that. I saw the latest changes you made to the macro, which, I think, isn't functional in the current state? It seems to have these issues (disclaimer: I haven't tested it yet, I'm following along with the logic, which to be honest, doesn't seem to be entirely correct in dbt-core either):
1. The temp relation gets the same name as the target relation, because `suffix` in  [`dremio__make_temp_relation`](https://github.com/dremio/dbt-dremio/blob/fad73d9c5f5aa1953aa64d24a3d2f6c01c125f63/dbt/include/dremio/macros/adapters/relation.sql#L15) doesn't get a default value like it does in [dbt-core](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/adapters/relation.sql#L13). 
2. The incremental sql is build off off the [intermediate relation](https://github.com/dremio/dbt-dremio/blob/main/dbt/include/dremio/macros/materializations/incremental/incremental.sql#L70) instead of the temp relation like it is in [dbt-core 1.3](https://github.com/dbt-labs/dbt-core/blob/1.3.latest/core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql#L55).

With regard to the use of a temporary table: if the model that defines the incremental query is not idempotent, or when the data fetch is very expensive, it see the use for a temporary table to fall back on when the load fails. In nearly all cases though, at least in my context, I fetch a specified daily increment from raw files (gzipped new line json mostly) that are already on S3, apply the schema and append it to an Iceberg table. There's no benefit to storing the data as a temporary table first. With the large volume of data I'm dealing with, the incurred overhead is significant. 

Also, if I would need a temporary location to load the data into first, I'd much much rather use Arctic instead and load the data on a new branch before committing it. 

If you would like to preserve current behaviour, which I can understand as it's in line with dbt-core, maybe caching the data in a temp table could be made optional? 

Let me know what you think, I'm willing to help get this right.

**Comment by ArgusLi** [comment]
Hi Marnix,

Thanks for being willing to help! We'd like to preserve the current behaviour to stay in line with dbt-core for now. Making caching the data in a temp table optional is definitely an interesting idea to explore. 

I've spun up the following issues to address your comment:
- https://github.com/dremio/dbt-dremio/issues/123
- https://github.com/dremio/dbt-dremio/issues/124
- https://github.com/dremio/dbt-dremio/issues/125

We'd be happy to have you help out and submit PRs if you'd like! If not we will get to these issues, although we cannot make any promises about a timeline at the moment.

Thanks for bringing up these issues!

**Comment by ArgusLi** [comment]
Closing this issue as they have been split into their own issues.

**Comment by fabrice-etanchaud** [comment]
Hi @Marnixvdb , @ArgusLi , what about using the new ROLLBACK command ? I can remember incremental materialization only accepts iceberg format.

**Comment by ArgusLi** [comment]
@fabrice-etanchaud The ROLLBACK command is quite interesting, let me do some more investigation and see if it's worthwhile to implement in the connector. My concern is can we manually trigger snapshots?
