### ISSUE TITLE
Temp tables stay in source

### ISSUE THREAD

**Issue by andersbogsnes** [dremio/dbt-dremio#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After running an incremental materialization, the tmp table remains in the source.

### Expected Behavior

No temp tables to remain after running dbt

This was the behavior in 1.3.0 and we would prefer to not have doubles of our data

### Steps To Reproduce

1. Define an incremental materialization
2. Run the materialization
3. Observe new dataset created in source

### Environment

```markdown
- OS: Windows
- dbt-dremio: 1.3.2
- Dremio Software: yes
- Dremio Cloud:
```

**Comment by ravjotbrar** [comment]
Thanks for raising this bug! We will be sure to look into it.

**Comment by ArgusLi** [comment]
@andersbogsnes Hi! Could you provide a little more information? Are you referring to a table with a `____dbt_tmp` suffix being created in object_storage_source that remains after running your models? Or are you referring to a view that is created in the dremio_space?

**Comment by andersbogsnes** [comment]
Hi @ArgusLi, yes, the tables with the _dbt_tmp suffix are being persisted in the object storage.

**Comment by ravjotbrar** [comment]
Hi both, I was able to reproduce this. Investigating what change in 1.3.2 caused this issue and will come out with a fix as soon as I pinpoint the cause.

**Comment by ravjotbrar** [comment]
Hi @andersbogsnes, I've merged a fix into our main branch. If you would like to try out this fix before our next release, please feel free to clone the repo and [install the local dbt-dremio](https://pip.pypa.io/en/stable/topics/local-project-installs/).

**Comment by andersbogsnes** [comment]
Great, thanks! I'm on parental leave so won't have access to my Dremio instance for a few weeks, but looking forward to trying it out as soon as I get back!

**Comment by davideromano** [comment]
Hi, I faced the same problem mentioned by @andersbogsnes.
Following this issue thread I read about the fix that @ravjotbrar merged into main branch.
I tried it and **it works as expected**: 
- Source S3: `__dbt_tmp` has been removed (both table and physical files)
- Source Glue: `__dbt_tmp` has been removed from the catalog and not the physical files ([Dremio Cloud DROP TABLE documentation](https://docs.dremio.com/cloud/sql/commands/drop-table/))

**Comment by jlarue26** [comment]
Great job @ravjotbrar !
