### ISSUE TITLE
Removal of drop table if exists "no_schema"."$scratch"

### ISSUE THREAD

**Issue by Alain-Barrette** [dremio/dbt-dremio#149]
### Describe the enhancement requested

Deployment of our code take a lot of time. We are currently deploying 1,025 object in 16minutes. Lots of this is due to 

/* {"app": "dbt", "dbt_version": "1.4.1", "profile_name": "cbq", "target_name": "qa", "node_id": "model.cbq.DeclarationAnnuelleAMFLegacyApplication3JeuxDonneesPolicesEnVigueurFinAnnee"} */
drop table if exists "no_schema"."$scratch"."DeclarationAnnuelleAMFLegacyApplication3JeuxDonneesPolicesEnVigueurFinAnnee"

This drop take between 1 and 22 seconds here. It depends on the load of the server and the Thread level we are using. 

![image](https://user-images.githubusercontent.com/57188421/223106328-c06499cd-d585-4cc3-82e0-a538e3cd1ad9.png)

Since there will never be an object name "no_schema"."$scratch".%, I don't see the need for this. 
Is it possible to have this removed ? 

### Justification for this enhancement

Speed increase during deployment.

**Comment by fabrice-etanchaud** [comment]
Bonjour @Alain-Barrette ,
(sorry I have to proceed in my poor english)
it seems to be an issue in the rendering of your model as a relation.
could you please give me its configuration parameters ?
I mean : 
- materialization type
- database
- schema
- datalake
- root_path

My two cents : the adapter's python code might have been updated,
Can you confirm that you want your model to be located as : 
$scratch.DeclarationAnnuelleAMFLegacyApplication3JeuxDonneesPolicesEnVigueurFinAnnee ?
I will try to understand why the adapter emit a relation like this : 
"no_schema"."$scratch"."DeclarationAnnuelleAMFLegacyApplication3JeuxDonneesPolicesEnVigueurFinAnnee"

Désolé,
Cordialement
Fabrice

**Comment by Alain-Barrette** [comment]
Hi @fabrice-etanchaud , 

No problems continuing in french if you like. In the meantime, I am adding the main data engineer that is working with dbt here.

Alexandre Cote will be reviewing this to answer you. We may indeed have some bad configuration in this project. 

Thanks

**Comment by ravjotbrar** [comment]
Hi @Alain-Barrette and @fabrice-etanchaud , If I understand the situation correctly, this drop table happens when QBC is trying to create views?

I see in the relevant create_or_replace_view macro we have a call to drop the table with the same name as the view:

```
  -- setup: in case the model was materialized before, drop the table
  {{ adapter.drop_relation(target_table) }}
```
@fabrice-etanchaud do you know the reasoning for why this was added?

**Comment by Alain-Barrette** [comment]
[dbt_project.zip](https://github.com/dremio/dbt-dremio/files/10919829/dbt_project.zip)

This could probably help.

**Comment by alexcotecbq** [comment]
Removing **datalake** and **root_path** from the **dbt_project.yml** file does not seem to avoid the **drop table** instruction.

Note that there is no functional impact from this issue, only a possible optimization.

**Comment by fabrice-etanchaud** [comment]
> Removing **datalake** and **root_path** from the **dbt_project.yml** file does not seem to avoid the **drop table** instruction.
> 
> Note that there is no functional impact from this issue, only a possible optimization.

I can't explain this

**Comment by Alain-Barrette** [comment]
This change result in a scratch drop.. 
![image](https://user-images.githubusercontent.com/57188421/223740743-79a852a1-1fa2-43ef-9dec-29fefd730874.png)
![image](https://user-images.githubusercontent.com/57188421/223740649-39288bd4-20ca-4bb5-ac95-d9b6998d1df1.png)

**Comment by fabrice-etanchaud** [comment]
That's better !

Please, take into account this : 

> no_schema is only meaningful for root_path or schema configurations,
> as a way to locate your model straight under the space or s3/hadoop/nfs root location.

So you shouldn't configure your project's default database to 'no_schema' (unless your space is named like this ?)

What is the materialized configuration of your "PlatiniumCrc..." model ?
I guess it's a view, and that you did not set any twin_strategy configuration, so defaulting to clone, and that the drop table command is emitted by the twin_strategy, that prevent a model to be materialized once as a view and once as a table.

Are you still experiencing long drop times ?

**Comment by Alain-Barrette** [comment]
The drop time depends on the load of dremio. At the moment we are testing with a small number of object. To reduce test time. Will do further testing when this issue is resolved

**Comment by Alain-Barrette** [comment]
Would it be easier to diagnose this by booking a meet between @fabrice-etanchaud  and @alexcotecbq

**Comment by alexcotecbq** [comment]
@fabrice-etanchaud : we can even talk in French if you want :-)

**Comment by fabrice-etanchaud** [comment]
Why not ?
But the diagnosis is done, since it's expected behavior, provided that you confirm that : 

> What is the materialized configuration of your "PlatiniumCrc..." model ?
> I guess it's a view, and that you did not set any twin_strategy configuration, so defaulting to clone, and that the drop table command is emitted by the twin_strategy, that prevents a model from being materialized once as a view and once as a table.

**Comment by alexcotecbq** [comment]
We don't have any documentation on the twin_strategy so no configuration.

**Comment by fabrice-etanchaud** [comment]
Dremio team wrote a wiki : https://github.com/dremio/dbt-dremio/wiki/Using-Materializations-with-Dremio#optional-twin-strategy-configuration

I am currently on my office time (I created dbt-dremio on my spare time three years ago, it's now maintained by dremio officially !),
I would be available after 6 PM CET(GMT+1).
How could we proceed ?

**Comment by alexcotecbq** [comment]
OK, we were recently looking at the Dremio and DBT websites so I wasn't aware of the option.
It seems to work with **allow** value for twin_strategy.
Thanks @fabrice-etanchaud

**Comment by fabrice-etanchaud** [comment]
Yes, twin_strategy is not an original dbt configuration, it's specific to dremio.

**Comment by fabrice-etanchaud** [comment]
Glad to hear it worked as expected !
I am so thankful to the dremio team for bringing the adapter to the next level, an enterprise grade adapter !

**Comment by fabrice-etanchaud** [comment]
Did you try to tell dbt to process more than 4 models at the same time (with regards to your DAG) ?

https://docs.getdbt.com/reference/dbt-jinja-functions/target

**Comment by Alain-Barrette** [comment]
testing was done with thread 8 and 16. No performance difference with both level. Will do further testing later when we hit the 1,500 objects mark in our project.

**Comment by ravjotbrar** [comment]
It seems like we might need to consider removing "clone" as the default twin_strategy option and make it "allow" instead.

**Comment by fabrice-etanchaud** [comment]
in a standard db engine, views and tables share the same namespace, and in dbt, when a given model changes from table to view, or from view to table, the previous table or view is of course replaced by the new view or table.
That's not true anymore in dremio : when you change the materialized configuration of a model, the previous table or view remains because they don't live in the same namespace (space or  source). That's why i introduced the twin strategy.
I really like to have for each table a kind of proxy view in a space, in order to have all the sql objects at the same place, like in a regular db engine "schema".
Finally, for non auto promoted format datasets, creating a proxy view is the only way to apply the format and emulate auto promotion...

**Comment by alexcotecbq** [comment]
@fabrice-etanchaud : By the way, is it possible to use a sys table with the adapter?  No CREATE VDS instruction is passed to Dremio in my case.  Here is the code in the .sql file:

`select distinct role_name as roleName from {{ source("dremio_internal_sys", "membership") }} order by role_name`

And here is the code in the .yml file:

```
sources:
  - name: dremio_internal_sys
    database: sys
    schema: no_schema
    tables:
      - name: membership

models:
  - name: DistinctRoles
    config:
      materialized: view
      alias: listRole
```

My colleague @Alain-Barrette would like to include administration views in Dremio via DBT.

**Comment by alexcotecbq** [comment]
Yes I am sure because the path is TravailEquie.EquipeData and DBT message is:

```
There are 2 unused configuration paths:
- models.cbq.TravailEquipe.CroixBleue
- models.cbq.TravailEquipe.CanAssistance
```

**Comment by fabrice-etanchaud** [comment]
Merci @alexcotecbq, je ne connaissais pas l'expression ! Bonne "fin de semaine" !
