### ISSUE TITLE
HIGH PRIORITY (workaround): Automatically update `dbt_project.yml` to disable reflections when connecting with non-admin account

### ISSUE THREAD

**Issue by jlarue26** [dremio/dbt-dremio#18]
When using a non-admin account, the following needs to be added to the bottom of the `dbt_project.yml` file at the root of the Dremio Cloud dbt project directory:

```
vars:
  dremio:reflections_enabled: false
```

This should be added automatically.

**Comment by ArgusLi** [comment]
Also figure out why it is doing sys table reflection calls.

**Comment by ArgusLi** [comment]
@fabrice-etanchaud thanks for the information you provided. We are concerned with most users of the adapter not having admin privileges. It appears that there is no way to access reflections without admin privileges. Therefore the question is how to by default disable the reflection materialisation instead of the current default which enables it. 

Would you happen to know?

**Comment by fabrice-etanchaud** [comment]
Easier said than done : If there is no such restriction with the API, now that you added API support, the call to the reflections system table in the catalog macros could be replaced with an API call to get the list of reflections, and the results unioned with the SQL based VDS and table list. Or maybe get the whole list of reflections + tables + vds via API ?

**Comment by fabrice-etanchaud** [comment]
Maybe we could replace true by false here : 

https://github.com/dremio/dbt-dremio/blob/340bfcefa282bd575d202cc8b2d07c122813c2f5/dbt/include/dremio/macros/adapters/metadata.sql#L28

and here : 

https://github.com/dremio/dbt-dremio/blob/340bfcefa282bd575d202cc8b2d07c122813c2f5/dbt/include/dremio/macros/materializations/reflection/reflection.sql#L16

I hope I can find more time to help next week, I will be on vacation.

**Comment by ArgusLi** [comment]
Even looking at the Rest API documentation, listing all tables is admin only, however users without admin privileges can look at reflection summaries.

Thanks for the information Fabrice, that saves me a lot of time. I think having reflections defaulting to off is only a temporary solutions, we'd definitely like to provide reflections. Just using drop and create is definitely an interesting approach. I'll take a closer look at it, thank you!

Enjoy your vacation!
