### ISSUE TITLE
Add ability to execute "call statement" and "run_query" on Dremio

### ISSUE THREAD

**Issue by mxmarg** [dremio/dbt-dremio#197]
### Describe the enhancement requested

Currently, adding Jinja template code for "call statement" and "run_query" in a Dremio dbt model sends an empty CREATE VDS statement to Dremio, which fails:

`/* {"app": "dbt", "dbt_version": "1.5.2", "profile_name": "dbt_model", "target_name": "sandbox", "node_id": "model.run_query"} */

  create or replace view "TEST_SPACE"."dbt_models"."run_query" as (
  )`

- https://docs.getdbt.com/reference/dbt-jinja-functions/statement-blocks
- https://docs.getdbt.com/reference/dbt-jinja-functions/run_query

### Justification for this enhancement

"Call statement" and "run_query" add the ability to execute arbitrary SQL as part of a dbt model, similar to pre- and post-hooks.

**Comment by Conq1** [comment]
They seem to work fine for me.
Do you use them inside macros or directly in the model? 

As a test I tried creating this model: 
```
select * from
{{ run_query("select * from information_schema.views") }}

```
Result:
```
create or replace view "testspace"."cmm_test" as (
select * from
| column          | data_type |
| --------------- | --------- |
| TABLE_CATALOG   | Text      |
| TABLE_SCHEMA    | Text      |
| TABLE_NAME      | Text      |
| VIEW_DEFINITION | Text      |
  )
```
Doesn't make much sense, but it did run the query. :)

**Comment by mxmarg** [comment]
Hi Christian,

thanks for taking the time to provide a better (and simpler) example than the official dbt documentation!
Looks like I had a fundamental misunderstanding about how those statements work in dbt, thanks for clearing it up :)
I will close this feature request.
