### ISSUE TITLE
[Bug]: reflection generation is broken

### ISSUE THREAD

**Issue by donatobarone** [dremio/dbt-dremio#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Let's assume I have 1 model which creates a view, let's call this model a.sql:

```sql

{{ config(
    materialized='view'
) }}

SELECT field1, field2, field3
FROM  {{ ref('table1') }} as t1

LEFT JOIN  {{ ref('table2') }} AS t2 ON t2.key2 = t1.key1

```

And then I create a new model called a_reflection.sql:

```sql
{{ config(materialized = 'reflection', reflection_type = 'raw') }}

-- depends_on: {{ [ref('a')] }}

```
This will actually fail with the following error:

After a bit of investigation and learning how the macro works, it is failing here https://github.com/dremio/dbt-dremio/blob/main/dbt/include/dremio/macros/materializations/reflection/reflection.sql#L30, because it is accessing twice the 0 index of refs, but in my example refs is an array with only 1 dict element:
```python
	'refs': [{
		'name': 'a'
	}]
```
So when trying to access the second 0 index it fails. I tried to modify the access to be **model.refs[0]['name']** and that succeeded in generating the reflection. 

### Expected Behavior

I am not sure if this is expected behaviour and I am doing something wrong, or this is just a bug

### Steps To Reproduce

1. Create model to generate reflection on top 
2. dbt build

### Environment

```markdown
- OS: Monterey 12.5.1
- dbt-dremio: 1.5.0
- Dremio Software: 23.1.5
- Dremio Cloud: N/A
```

**Comment by Conq1** [comment]
Think this one is already mentioned a few time. At least this one is the same:
https://github.com/dremio/dbt-dremio/issues/193

**Comment by donatobarone** [comment]
Closing the issue in favour of #193
