### ISSUE TITLE
Requesting Table Merge Functionality in dremio-dbt for Apache Iceberg Tables

### ISSUE THREAD

**Issue by ijtarano** [dremio/dbt-dremio#224]
### Describe the enhancement requested

During a recent session with the Dremio team, it was communicated that merge functionality for Apache Iceberg tables is not yet supported in the dremio-dbt project.

### Justification for this enhancement

This feature would be particularly beneficial for the team at Cepsa as we increasingly work with Apache Iceberg tables within the context of our lakehouse architecture.

**Comment by ravjotbrar** [comment]
Hi @ijtarano! Thanks for raising this request.The merge strategy is currently in progress.
