### ISSUE TITLE
dbt-core 1.2 upgrade: Connection Retries

### ISSUE THREAD

**Issue by jlarue26** [dremio/dbt-dremio#40]
From https://github.com/dbt-labs/dbt-core/discussions/5468:

> https://github.com/dbt-labs/dbt-core/pull/5432 adds a new method to the BaseAdapter, retry_connection() ([source](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/base/connections.py#L180-L266)), that allows an adapter to automatically try again when the attempt to open a new a connection on the database has a transient, infrequent error. The option can be set using the retries config in the target of a ~/.dbt/profiles.yml
> 
> If relevant to your adapter, you'll need to implement the following changes in your adapters connections.py:
> 
> Add the retries value to the connection manager class along with it's default number of times to retry (likely: 1?)
> in the ConnectionManager.open() method:
> an intra-method function: connect() ([postgres's implementation](https://github.com/dbt-labs/dbt-core/blob/1.2.latest/plugins/postgres/dbt/adapters/postgres/connections.py#L125-L137)) that returns a handle object. A handle is the object returned by the standard python DB2 API Cursor object immediately after attempting to connect
> a list of retryable_exceptions of exceptions ([dbt-postgres' version](https://github.com/dbt-labs/dbt-core/blob/1.2.latest/plugins/postgres/dbt/adapters/postgres/connections.py#L139-L146)) sthe underlying driver might expose.
> the return value of the .open() method is now a call to cls.retry_connection()` ([dbt-postgres's version](https://github.com/dbt-labs/dbt-core/blob/1.2.latest/plugins/postgres/dbt/adapters/postgres/connections.py#L148-L154))

**Comment by ArgusLi** [comment]
After a quick discussion with @jlarue26 and @ravjotbrar, we've decided to add more exceptions the underlying wrapper for the rest api can expose.

By then adding these exceptions to the list of retryable_exceptions and adding a retry_timeout to retry_connections(), we should be able to provide a more elegant solution to https://github.com/dremio/dbt-dremio/issues/22.
