### ISSUE TITLE
dbt-core 1.2 upgrade: Cross-database Macros

### ISSUE THREAD

**Issue by jlarue26** [dremio/dbt-dremio#41]
From https://github.com/dbt-labs/dbt-core/discussions/5468:

> In https://github.com/dbt-labs/dbt-core/pull/5298, we migrated a collection of ["cross-database macros"](https://github.com/dbt-labs/dbt-core/discussions/cross-database-macros) from [dbt-utils](https://github.com/dbt-labs/dbt-utils) to dbt-core. Default implementations are automatically inherited by adapters and included in the testing suite. Adapter maintainers may need to override the implementation of one or more macros to align with database-specific syntax or optimize performance. For details on the testing suite, see: ["Testing a new adapter"](https://github.com/dbt-labs/dbt-core/discussions/testing-a-new-adapter).
> 
> The TL;DR rationale for this work is:
> 
> Simplify dbt-utils development
> Allow some packages to no longer depend on dbt-utils as a package
> Provide adapter maintainers tests that can but used in the adapter repo CI, as opposed to in a shim package
> As for how to make it happen, looking at the following PRs for dbt-Labs-maintained adapters show it clearly:
> 
> https://github.com/dbt-labs/dbt-bigquery/pull/192
> https://github.com/dbt-labs/dbt-redshift/pull/120
> https://github.com/dbt-labs/dbt-snowflake/pull/162

**Comment by ravjotbrar** [comment]
Since, default implementations are automatically inherited by adapters and included in the testing suite, any issues related to these macros would become apparent when running the tests. All tests currently pass and any issues (including timestamp) were addressed in [basic func tests](https://dremio.atlassian.net/browse/DX-56929). Closing.
