### ISSUE TITLE
dbt-core 1.2 upgrade: BaseDocsGenerate and BaseDocsGenReferences

### ISSUE THREAD

**Issue by jlarue26** [dremio/dbt-dremio#43]
From https://github.com/dbt-labs/dbt-core/discussions/5468:

> https://github.com/dbt-labs/dbt-core/pull/5058 is another step along https://github.com/dbt-labs/dbt-core/issues/4788 to the new framework in order to empower adapter maintainers and other contributors to make use of the same tests that the core team uses for their own adapters. Effectively, this test is validates an adapter's ability to correctly generate the catalog that serves as the static backend of a project docs site.
> If your adapter does not add extra relation-level metadata (e.g. table size (rows + bytes), last modified timestamp) which is the case by default, then you can follow the same inherit and pass pattern to enable your version of BaseDocsGenerate and BaseDocsGenReferences. However, if you are supplementing the catalog with more metadata, you'll have to:
> 
> Add a method that defines stats for this adapter [e.g. dbt-bigquerys](https://github.com/dbt-labs/dbt-bigquery/blob/main/tests/functional/adapter/expected_stats.py)
> Reimplement the expected_catalog fixture, [passing the above into model_stats and seed_stats](https://github.com/dbt-labs/dbt-bigquery/blob/0212fd621ede4c24929a008de718a7e45bc32cec/tests/functional/adapter/test_basic.py#L68-L81)
> Example PRs:
> 
> https://github.com/dbt-labs/dbt-bigquery/pull/190
> https://github.com/dbt-labs/dbt-redshift/pull/116

**Comment by ravjotbrar** [comment]
Since, default implementations are automatically inherited by adapters and included in the testing suite, any issues related to these macros would become apparent when running the tests. All tests  currently pass and any issues (including timestamp) were addressed in [basic func tests](https://dremio.atlassian.net/browse/DX-56929). Closing.
