### ISSUE TITLE
dbt-core 1.3 upgrade: Incremental mats: more standard and more error-proof

### ISSUE THREAD

**Issue by jlarue26** [dremio/dbt-dremio#44]
From https://github.com/dbt-labs/dbt-core/discussions/6011: 

> user-facing changes
> new in 1.3:
> breaking change. the default strategy of incremental models used to be delete+insert. it is now append. See point below to override this.
> a new macro, adapter_get_incremental_default_sql(), in which adapter maintainers can specify a 'default' strategy for incremental models.
> a new Adapter method, valid_incremental_strategies() in which adapter maintainers can define all supported strategies. Previously, if i user defined an unsupported incremental strategy, they would not learn of their error until compile time or later. Now dbt will throw an error before attempting to compile.
> non-user facing changes
> there was significant work (https://github.com/dbt-labs/dbt-core/issues/5245 https://github.com/dbt-labs/dbt-core/pull/5359) put into refactoring the default incremental materialization. If your adapter overrides the default, we recommend that you either:
> 2. refactor your materialization to match that of the default
> even better, determine exactly why you currently need to override the default, and perhaps we can find a way to bring that flexibility into the core adapter so that you can stay up to date with the default mat

**Comment by ArgusLi** [comment]
Not in the scope of our current dbt strategy.
