### ISSUE TITLE
When only space is provided with no schema, the space isn't being created

### ISSUE THREAD

**Issue by ArgusLi** [dremio/dbt-dremio#58]
When a new space is assigned in profiles.yml but no schema is assigned, the view cannot be created because the space isn't created.

Note: it doesn't call create_catalog().

**Comment by fabrice-etanchaud** [comment]
Hi @ArgusLi ,

I am afraid we won't be able to change that behavior, as it seems to be located here in the dbt-core code : 

https://github.com/dbt-labs/dbt-core/blob/f02243506df2a9b6851abe6bcfe10af8808d41cc/core/dbt/task/runnable.py#L568

But don't you think space creation should be an administrative task, and that dbt should only operate on already existing "databases" - spaces and data lakes ?

#67 is a related issue.

**Comment by ArgusLi** [comment]
Hi @fabrice-etanchaud,

Thanks for the additional information. I agree that space creation should be an administrative task. As such, I will update our documentation to make this a pre-condition.

Thanks for your help!
