### ISSUE TITLE
type_string return string/text instead of varchar

### ISSUE THREAD

**Issue by nicodp-leap** [dremio/dbt-dremio#78]
When using the macro` dbt_utils.union_relations` I got an error on Dremio because the macro `type_string` (used inside union_relations) returns `STRING` instead of `VARCHAR`. Dremio does not recognise the keyword STRING, so the query fails.

**Comment by ArgusLi** [comment]
Hi @nicodp-leap, thanks for creating an issue. We will be looking into this.
